timezone_detect.settings:
  type: config_object
  label: 'Timezone detect settings'
  mapping:
    mode:
      type: string
      label: 'Mode which the timezone will be detected.'
    watchdog:
      type: boolean
      label: 'Log changes to timezone.'